# Generated by Django 3.1.2 on 2020-10-22 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qiita_app', '0003_auto_20201021_0713'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultLonger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=240)),
                ('value', models.IntegerField()),
            ],
        ),
    ]
